### PR TITLE
Added Strawberry and Tomato GH Data

### PR DESCRIPTION
**Pull request by mac234**
Data from recent experiments comparing fruit grown with the LASSI lighting algorithm to CO2LASSI algorithm.

### CODE REVIEW

**Comment by zer0n** [comment]
It's better to use CSV (text) format instead of Excel. Excel are binary and can't be rendered on the web or version controlled easily. 


image

**Comment by mac234** [comment]
I agree CSV has advantages.  Does this imply that Excel files will not be accepted?

**Comment by mac234** [comment]
Thanks.

I have removed the Excel and uploaded CSV files.

I might suggest changing " CSV is recommended over Excel" to " CSV is required over Excel" in the data guide to help keep data submitters on the correct track.

**Comment by zer0n** [comment]
What is the `rtf` file? 

We should use the markdown file (`README.md`) because it can be displayed natively on GitHub. See example [here](https://github.com/CEAOD/Data/blob/master/GH_Cucumber/MicrosoftResearch/README.md)

image

**Pull request merged**
